---
title: "Publication in the Science in Parliament Magazine"
subtitle: "Geographic data science for policy research and impact"
draft: false
author: "Francisco Rowe"
date: '2024-10-03'
categories: [""]
tags: ["Geographic data science", "mobility", "digital data"]
---

I had an interesting experience contributing to a publication for [The Journal of the Parliamentary and Scientific Committee – All-Party Parliamentary Group](https://www.scienceinparliament.org.uk/publications/science-in-parliament/), communicating the potential of geographic data science for policy making and the some of work we have done at the [Geographic Data Science Lab (GDSL)](https://www.liverpool.ac.uk/geographic-data-science/). In particular, I describe how we (at the GDSL) have used geographic data to monitor human mobility (the migration, displacement or planned relocation of people) to support emergency responses to natural disasters and humanitarian crises – estimating service demand, improving population forecasting, and informing spatial planning. 

Read below the snippets of the text I wrote with some links to some of the work I refer to:


* **MONITORING HUMAN MOBILITY TO SUPPORT EFFECTIVE EMERGENCY RESPONSES: Professor Francisco Rowe**

*In the GDSL at the University of Liverpool we harness [geographic data](https://doi.org/10.4337/9781800883499.ch09) to monitor human mobility (the migration, displacement or planned relocation of people) to support emergency responses to natural disasters and humanitarian crises – estimating service demand, improving population forecasting, and informing spatial planning.*

*Established evidence on human mobility predominantly relies on traditional data sources but they can only offer static geographic representations of human mobility at single points in time. As such, their ability to provide timely insights into sudden or short-term changes in human mobility, including in health emergencies such as the COVID-19 pandemic, or in natural disaster events caused by [flooding](https://doi.org/10.1080/21681376.2022.2135458) or [wildfires](), is limited and hence, their capacity to enable appropriately rapid policy responses is also limited. By using location data from digital technology, we have been able to measure and monitor human mobility flows in near real-time at small area levels over short, hourly time intervals. We have worked with national government agencies and transitional organisations to support their plans and operations.*

*We are currently collaborating with the Liverpool City Region Combined Authority to create a [composite index](https://doi.org/10.1016/j.compenvurbsys.2024.102179) of transport demand and supply to identify potential areas in need of suitable infrastructure to promote active travel. We have also generated evidence for Ajuntament de Barcelona (the City Council of Barcelona) to inform the design of [15-minute neighbourhoods](https://doi.org/10.1371/journal.pone.0250080).*

*We have assisted the UN International Organisation for Migration (IOM) to respond to the ongoing humanitarian crisis triggered by the war in Ukraine by [identifying potential settlement areas](https://doi.org/10.1002/psp.2790) of refugees across Europe, estimating the extent and key destinations of population displacement within Ukraine. We have also partnered with the United Nations in Latin America to assess the [impact of the COVID-19 pandemic on population movements](https://www.cepal.org/en/publications/type/population-and-development) from large cities, directly contributing to their flagship “Inclusive and Sustainable Smart Cities” project.*


